python src/analysis/predict/deep_learning/assess_tuned.py \
    --gpus=1 \
    --max_epochs=200 \
    --batch_size=25 \
    --val_batch_size=20 \
    --is_eigimg \
    --slice_start=125 \
    --slice_end=175 \
    --conv_in_channels=50 \
    --conv_out_channels=50 \
    --conv_num_layers=4 \
    --conv_kernel_size=7 \
    --conv_dilation=2 \
    --conv_residual \
    --conv_norm=batch \
    --conv_norm_groups=5 \
    --conv_cbam \
    --conv_cbam_reduction=4 \
    --lstm_num_layers=2 \
    --lstm_hidden_sizes=4 \
    --lstm_kernel_sizes=3 \
    --lstm_dilations=2 \
    --lstm_norm=group \
    --lstm_norm_groups=2 \
    --lstm_inner_spatial_dropout=0.2 \
    --lr=2e-4 \
    --l2=2e-7
